#spring.profiles.active: 'local'
app.heading: "COVID-19 T R A C K E R"
spring.application.name: covid-19-frontend
server.port: 8080

covid19.service.api:
  base: 'https://track-covid19-api.herokuapp.com'
  report:
    date: '${covid19.service.api.base}/covid-19/report'
    all: '${covid19.service.api.base}/covid-19/report/all'
    country: '${covid19.service.api.base}/covid-19/report/country'
  user:
    name: "${COVID_API_USERNAME}"
    password: "${COVID_API_PASSWORD}"

spring.mvc.static-path-pattern: '/static/**'

app.notifications.email:
  address: 'charatha@gmail.com'

